server:
  port: 8082

---

spring:
  profiles: dev
  application:
    name: Spring-boot-start
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/spring_start?useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to spring boot learning

---

spring:
  profiles: qa
  application:
    name: Spring-boot-start
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/spring_start?useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to spring boot learning